### ISSUE TITLE
Question about the loss of 'Fog-pass Filtering Modules'

### ISSUE THREAD

**Issue by tiamjiakun** [sohyun-l/fifo#5]
Hello, when I read the paper I noticed that in equation 1 after calculating the difference between the cosine distance and m you also need to square the difference. But your code does not square the difference, how do you explain this difference between the code and equation 1 of the paper?

**Comment by sohyun-l** [comment]
Thank you for your detailed comment. 
In our implementation, we opted to use the L1 distance as the difference metric for the cosine distance, instead of squaring the difference. However, using the L2 distance would also be viable for learning the metric, and it does not pose a problem. Since this is not a loss term that directly contributes to invariance, the choice between L1 and L2 distances does not significantly affect the results.
